src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    use ResourceId;
    use Timestapable;

    const GENRE_HOMME = 'Man';
    const GENRE_FEMME = 'Woman';
    const GENRE_AUTRE = 'Other';

    const ROLE_CANDIDAT = 'ROLE_CANDIDAT';

    const EN_ATTENTE = 0;
    const ACCEPTEE = 1;
    const REFUSEE = 2;

    const COMPTE_ACTIF = 3;
    const COMPTE_SUPPRIME = 4;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private ?string $email;

    /**
     * @ORM\Column(type="json")
     */
    private array $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string", nullable=true)
     */
    private string $password;

    /**
     * @ORM\OneToMany(targetEntity=File::class, mappedBy="user")
     */
    private Collection $files;

    /**
     * @ORM\ManyToMany(targetEntity=Project::class, mappedBy="auteur")
     */
    private Collection $projects;

    /**
     * @ORM\Column(type="boolean")
     */
    private bool $isVerified = false;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private ?string $nom;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private ?string $prenom;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private ?string $civilite;

    /**
     * @ORM\ManyToMany(targetEntity=Group::class, mappedBy="members")
     */
    private Collection $groups;

    /**
     * @ORM\OneToMany(targetEntity=Project::class, mappedBy="editor", cascade={"persist"})
     */
    private Collection $project_editor;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private ?bool $isDeleted;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private ?bool $isMentor;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private ?\DateTimeInterface $lastConnection;

    /**
     * @ORM\ManyToOne(targetEntity=Team::class, inversedBy="users")
     */
    private ?Team $team = null;

    public function __construct()
    {
        $this->files = new ArrayCollection();
        $this->projects = new ArrayCollection();
        $this->createdAt = new \DateTimeImmutable('now');
        $this->groups = new ArrayCollection();
        $this->project_editor = new ArrayCollection();
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @return string[]
     */
    public static function getGenreName(): array
    {
        return array(
            'Man' => User::GENRE_HOMME,
            'Woman' => User::GENRE_FEMME,
            'Other' => User::GENRE_AUTRE,
        );
    }

    /**
     * @return string[]
     */
    public static function getRoleNames(): array
    {
        return array(
            'Candidate' => User::ROLE_CANDIDAT,
        );
    }

    public function __toString(): string
    {
        return $this->nom;
    }


    /**
     * @return string
     */
    public function getFullname(): string
    {
        return $this->getPrenom().' '.$this->getNom();
    }

    public function checkRoles($role): bool
    {
        foreach($this->roles as $item)
        {
            if($item == $role)
            {
                return true;
            }
        }
        return false;
    }

    public function isCandidat(): bool
    {
        $role = "ROLE_CANDIDAT";
        return $this->checkRoles($role);
    }

    public function isMentor(): bool
    {
        $role = "ROLE_MENTOR";
        return $this->checkRoles($role);
    }

    public function isAdmin(): bool
    {
        $role = "ROLE_ADMIN";
        return $this->checkRoles($role);
    }

    public function isSuperAdmin(): bool
    {
        $role = "ROLE_SUPER_ADMIN";
        return $this->checkRoles($role);
    }

    public function getRoleName():string
    {
        if ($this->isSuperAdmin()){
            return 'Super Administrateur';
        }else if($this->isAdmin()){
            return 'Admin';
        }else if($this->isMentor()){
            return 'Mentor';
        }else if($this->isCandidat()){
            return 'Student';
        }else{
            return 'No info';
        }
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection
     */
    public function getFiles(): Collection
    {
        return $this->files;
    }

    public function addFile(File $file): self
    {
        if (!$this->files->contains($file)) {
            $this->files[] = $file;
            $file->setUser($this);
        }

        return $this;
    }

    public function removeFile(File $file): self
    {
        if ($this->files->removeElement($file)) {
            // set the owning side to null (unless already changed)
            if ($file->getUser() === $this) {
                $file->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection
     */
    public function getProjects(): Collection
    {
        return $this->projects;
    }

    public function addProject(Project $project): self
    {
        if (!$this->projects->contains($project)) {
            $this->projects[] = $project;
            $project->addAuteur($this);
        }

        return $this;
    }

    public function removeProject(Project $project): self
    {
        if ($this->projects->removeElement($project)) {
            $project->removeAuteur($this);
        }

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(?string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(?string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getCivilite(): ?string
    {
        return $this->civilite;
    }

    public function setCivilite(?string $civilite): self
    {
        $this->civilite = $civilite;

        return $this;
    }

    /**
     * @return Collection
     */
    public function getGroups(): Collection
    {
        return $this->groups;
    }

    public function addGroup(Group $group): self
    {
        if (!$this->groups->contains($group)) {
            $this->groups[] = $group;
            $group->addMember($this);
        }

        return $this;
    }

    public function removeGroup(Group $group): self
    {
        if ($this->groups->removeElement($group)) {
            $group->removeMember($this);
        }

        return $this;
    }

    /**
     * @return Collection
     */
    public function getProjectEditor(): Collection
    {
        return $this->project_editor;
    }

    public function addProjectEditor(Project $projectEditor): self
    {
        if (!$this->project_editor->contains($projectEditor)) {
            $this->project_editor[] = $projectEditor;
            $projectEditor->setEditor($this);
        }

        return $this;
    }

    public function removeProjectEditor(Project $projectEditor): self
    {
        if ($this->project_editor->removeElement($projectEditor)) {
            // set the owning side to null (unless already changed)
            if ($projectEditor->getEditor() === $this) {
                $projectEditor->setEditor(null);
            }
        }

        return $this;
    }

    public function IsDeleted(): ?bool
    {
        return $this->isDeleted;
    }

    public function setIsDeleted(?bool $isDeleted): self
    {
        $this->isDeleted = $isDeleted;

        return $this;
    }

    /**

src/Controller/MessagesController.php
<?php

namespace App\Controller;

use App\Entity\Email;
use App\Entity\Messages;
use App\Entity\User;
use App\Form\MessagesType;
use App\Repository\MessagesRepository;
use App\Repository\UserRepository;
use App\Service\Mailer;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Mailer\Exception\TransportExceptionInterface;
use Symfony\Component\Routing\Annotation\Route;
use Twig\Environment;
use Twig\Error\LoaderError;
use Twig\Error\RuntimeError;
use Twig\Error\SyntaxError;
use Twig\Loader\ArrayLoader;

#[Route('/message')]
class MessagesController extends AbstractController
{
    #[Route('/', name: 'messages')]
    public function index(MessagesRepository $messagesRepository, UserRepository $userRepository): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        $users = $userRepository->findBy(['isDeleted' => 0]);

        $groupmates = $userRepository->getGroupMembers($this->getUser());

        return $this->render('message/index.html.twig', [
            'controller_name' => 'MessagesController',
            'messageRepository' => $messagesRepository,
            'received' => $messagesRepository->getReceivedUsers($this->getUser()),
            'groupmates' => $groupmates,
            'users' => $users
        ]);
    }

    /**
     * @throws SyntaxError
     * @throws TransportExceptionInterface
     * @throws RuntimeError
     * @throws LoaderError
     */
    #[Route('/send', name: 'message_send')]
    public function send(MessagesRepository $messagesRepository, Request $request, Mailer $mailer, ManagerRegistry $doctrine): Response
    {
        $user = $this->getUser();
        $message = new Messages;
        $form = $this->createForm(MessagesType::class, $message, [
                        'user' => $this->getUser(),
                ]
        );

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $message->setSender($user);

            $parentid = $form->get("parentid")->getData();

            $em = $doctrine->getManager();
            if($parentid != null){
                $parent = $em->getRepository(Messages::class)->find($parentid);
            }

            $message->setParent($parent ?? null);
            $em->persist($message);
            $em->flush();

            $email = $em->getRepository(Email::class)->findOneBy(['code' => 'EMAIL_ENVOI_MESSAGE']);

            $loader = new ArrayLoader([
                    'email' => $email->getContenu(),
            ]);

            $twig = new Environment($loader);
            $messageMail = $twig->render('email', ['message' => $message->getMessage(), 'sender' => $user, 'recipient' => $message->getRecipient()]);

            $this->addFlash("success", "Message envoyé avec succès.");

            $mailer->send([
                    'recipient_email' => $message->getRecipient()->getEmail(),
                    'subject' => $message->getTitle(),
                    'html_template' => 'email/email_vide.html.twig',
                    'context' => [
                            'message' => $messageMail
                    ]
            ]);

            return $this->redirectToRoute("messages");
        }

        return $this->render("message/modal.html.twig", [
                "form" => $form->createView(),
                'received' => $messagesRepository->getReceived($this->getUser())
        ]);
    }

    /**
     * @throws SyntaxError
     * @throws TransportExceptionInterface
     * @throws RuntimeError
     * @throws LoaderError
     */
    #[Route('/reply/{id}', name: 'reply')]
    public function reply(Request $request, Mailer $mailer, User $user, ManagerRegistry $doctrine): Response
    {
        $em = $doctrine->getManager();
        $moi= $this->getUser();
        $reply = new Messages;

        $textReply = $request->request->get('reply');
        $ajax = $request->request->get('ajax');

        $reply->setSender($moi);
        $reply->setRecipient($user);
        $reply->setMessage($textReply);
        $reply->setTitle('Re: ');
        if ($ajax) {
            $reply->setIsRead(1);
        }else{
            $reply->setIsRead(0);
        }
        //$reply->setParent($message);

            $em->persist($reply);
            $em->flush();

            $email = $em->getRepository(Email::class)->findOneBy(['code' => 'EMAIL_ENVOI_MESSAGE']);
            if ($email) {
                $loader = new ArrayLoader([
                    'email' => $email->getContenu(),
                ]);

                $twig = new Environment($loader);
                $messageMail = $twig->render('email', ['message' => $reply->getMessage(), 'sender' => $moi, 'recipient' => $reply->getRecipient()]);

                $this->addFlash("success", "Message envoyé avec succès.");

                $mailer->send([
                    'recipient_email' => $reply->getRecipient()->getEmail(),
                    'subject' => 'Nouveau message sur Talents Handicap',
                    'html_template' => 'email/email_vide.html.twig',
                    'context' => [
                        'message' => $messageMail
                    ]
                ]);
            }
            if ($ajax){
                return new Response(1);
            }else{
                return $this->redirectToRoute('read',['id' => $user->getId()]);
            }


    }

    #[Route('/read/{id}', name: 'read')]
    public function read(User $user, MessagesRepository $messagesRepository, ManagerRegistry $doctrine, UserRepository $userRepository): Response
    {
        $groupmates = $userRepository->getGroupMembers($this->getUser());
        $em = $doctrine->getManager();
        $messagesReceived = $em->getRepository(Messages::class)->getAllMessagesReceivedNotRead($this->getUser(), $user);

        $users = $userRepository->findBy(['isDeleted' => 0 ]);

        foreach ($messagesReceived as $msg){
            $msg->setIsRead(1);
            $em->persist($msg);
        }
        $em->flush();

        $messages = $em->getRepository(Messages::class)->getAllMessages($this->getUser(), $user);

        return $this->render('message/read.html.twig', [
                'user' => $user,
                'message' => $messages,
                'received' => $messagesRepository->getReceivedUsers($this->getUser()),
                'groupmates' => $groupmates,
                'users' => $users
        ]);
    }

    public function messageNotReadBySender(User $user, ManagerRegistry $doctrine): Response
    {
        $em = $doctrine->getManager();
        $messages = $em->getRepository(Messages::class)->countMsgNotRead($this->getUser(), $user);
        return new Response("".$messages);
    }

    /**
     * @throws NonUniqueResultException
     */
    public function lastMessageReceived(User $user, MessagesRepository $messagesRepository): Response
    {
        $message = $messagesRepository->getLastMessage($this->getUser(), $user);

        return new Response("".$message);
    }

    #[Route('/all/message/{id}', name: 'ajax_all_messages')]
    public function allMessages(User $user, MessagesRepository $messagesRepository): Response
    {
        $messages = $messagesRepository->getAllMessages($this->getUser(), $user);
        return $this->render('message/_messages.html.twig', [
            'user' => $user,
            'messages' => $messages,
        ]);
    }
}

templates/message/answer.html.twig
{% extends 'base-dashboard.html.twig' %}

{% block title %}Messagerie{% endblock %}

{% block body %}
    <div class="post-a-new-job-box">
        <h3>Send message</h3>
        <div class="bar"></div>
        {{ form(form) }}
    </div>
{% endblock %}

templates/message/index.html.twig
{% extends 'base-dashboard.html.twig' %}

{% block title %}ChatBox{% endblock %}

{% block body %}

<div class="breadcrumb-area">
    <h1>Messages</h1>
    <ol class="breadcrumb">
        <li class="item"><a href="{{ path('home') }}.html">Home</a></li>
        <li class="item">Messages</li>
    </ol>
</div>

<div class="chat-content-area">
    <div class="sidebar-left">
        {{ include('message/sidebar.html.twig') }}
    </div>
    <div class="content-right">
        <div class="chat-area">
            <div class="chat-list-wrapper">
                <div class="chat-list">
                    <div class="chat-list-header d-flex align-items-center">
                        <div class="header-left d-flex align-items-center">
                            Click on any message or new contact...
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

templates/message/sidebar.html.twig
<div class="sidebar">
    <div class="chat-sidebar-header d-flex align-items-center">
        <div class="avatar me-3">
            {% if user.profile and user.profile.getPhoto()|length %}
                {% for avatar in user.profile.getPhoto() %}
                    {% if avatar.type is same as 1 %}
                        {% if loop.first %}
                            <img src="{{ asset('uploads/' ~ avatar.nom) }}" width="50" height="50" class="rounded-circle" alt="{{ user.getFullname() }}">
                        {% endif %}
                    {% endif %}
                {% endfor %}
            {% else %}
                <svg viewBox="0 0 36 36" fill="none" role="img" xmlns="http://www.w3.org/2000/svg" width="50" height="50"><title>{{ app.user.getFullname()|capitalize }}</title><mask id="mask__beam" maskUnits="userSpaceOnUse" x="0" y="0" width="36" height="36"><rect width="36" height="36" fill="#FFFFFF" rx="72"></rect></mask><g mask="url(#mask__beam)"><rect width="36" height="36" fill="#dde3ca"></rect><rect x="0" y="0" width="36" height="36" transform="translate(3 5) rotate(261 18 18) scale(1)" fill="#487aa1" rx="36"></rect><g transform="translate(-5 1) rotate(-1 18 18)"><path d="M13,19 a1,0.75 0 0,0 10,0" fill="#FFFFFF"></path><rect x="13" y="14" width="1.5" height="2" rx="1" stroke="none" fill="#FFFFFF"></rect><rect x="21" y="14" width="1.5" height="2" rx="1" stroke="none" fill="#FFFFFF"></rect></g></g></svg>
            {% endif %}
        </div>
        <form class="form-group position-relative mb-0">
            <label for="search-field"><i class="ri-search-line"></i></label>
            <input type="search" class="form-control" name="search-field" value="" placeholder="Search here..." id="myInput" onkeyup="myFunction()">
        </form>
    </div>

    <div class="sidebar-content d-flex chat-sidebar" data-simplebar>
        <div class="chat-menu">
            {% if received|length > 0 %}
            <label class="d-block list-group-label mt-0">Chats</label>

            <ul class="list-group list-group-user list-unstyled mb-0" id="myUL">
                {% for user in received %}
                    <li>
                        <a href="{{ path("read", {id: user.id}) }}">
                            <div class="d-flex align-items-center">
                                <div class="avatar me-3">
                                    {% if user.profile and user.profile.getPhoto()|length %}
                                        {% for avatar in user.profile.getPhoto() %}
                                            {% if avatar.type is same as 1 %}
                                                {% if loop.first %}
                                                    <img src="{{ asset('uploads/' ~ avatar.nom) }}" width="50" height="50" class="rounded-circle" alt="{{ user.getFullname() }}">
                                                {% endif %}
                                            {% endif %}
                                        {% endfor %}
                                    {% else %}
                                        <svg viewBox="0 0 36 36" fill="none" role="img" xmlns="http://www.w3.org/2000/svg" width="50" height="50"><title>{{ user.getFullname()|capitalize }}</title><mask id="mask__beam" maskUnits="userSpaceOnUse" x="0" y="0" width="36" height="36"><rect width="36" height="36" fill="#FFFFFF" rx="72"></rect></mask><g mask="url(#mask__beam)"><rect width="36" height="36" fill="#dde3ca"></rect><rect x="0" y="0" width="36" height="36" transform="translate(3 5) rotate(261 18 18) scale(1)" fill="#487aa1" rx="36"></rect><g transform="translate(-5 1) rotate(-1 18 18)"><path d="M13,19 a1,0.75 0 0,0 10,0" fill="#FFFFFF"></path><rect x="13" y="14" width="1.5" height="2" rx="1" stroke="none" fill="#FFFFFF"></rect><rect x="21" y="14" width="1.5" height="2" rx="1" stroke="none" fill="#FFFFFF"></rect></g></g></svg>
                                    {% endif %}
                                </div>

                                <div class="user-name">
                                    <h6>{{ user.getFullname() }}</h6>
                                    <span class="d-block">
                                        {{ render(controller('App\\Controller\\MessagesController::lastMessageReceived',{ 'user': user })) }}
                                        {% if render(controller('App\\Controller\\MessagesController::messageNotReadBySender',{ 'user': user })) > 0 %}
                                            {{ render(controller('App\\Controller\\MessagesController::messageNotReadBySender',{ 'user': user })) }}
                                        {% endif %}
                                    </span>
                                </div>
                            </div>
                        </a>
                    </li>
                {% endfor %}
            </ul>
            {% endif %}
            <label class="d-block list-group-label">Contacts</label>

            {% if not app.user.isSuperAdmin() %}
                <ul class="list-group list-group-user list-unstyled mb-0">
                    {% for group in app.user.groups %}
                        {% for user in group.members %}
                            {% if app.user.id != user.id %}
                                <li>
                                    <a href="{{ path("read", {id: user.id}) }}">
                                        <div class="d-flex align-items-center">
                                            <div class="avatar me-3">
                                                {% if user.profile and user.profile.getPhoto()|length %}
                                                    {% for avatar in user.profile.getPhoto() %}
                                                        {% if avatar.type is same as 1 %}
                                                            {% if loop.first %}
                                                                <img src="{{ asset('uploads/' ~ avatar.nom) }}" width="50" height="50" class="rounded-circle" alt="{{ user.getFullname() }}">
                                                            {% endif %}
                                                        {% endif %}
                                                    {% endfor %}
                                                {% else %}
                                                    <svg viewBox="0 0 36 36" fill="none" role="img" xmlns="http://www.w3.org/2000/svg" width="50" height="50"><title>{{ app.user.getFullname()|capitalize }}</title><mask id="mask__beam" maskUnits="userSpaceOnUse" x="0" y="0" width="36" height="36"><rect width="36" height="36" fill="#FFFFFF" rx="72"></rect></mask><g mask="url(#mask__beam)"><rect width="36" height="36" fill="#dde3ca"></rect><rect x="0" y="0" width="36" height="36" transform="translate(3 5) rotate(261 18 18) scale(1)" fill="#487aa1" rx="36"></rect><g transform="translate(-5 1) rotate(-1 18 18)"><path d="M13,19 a1,0.75 0 0,0 10,0" fill="#FFFFFF"></path><rect x="13" y="14" width="1.5" height="2" rx="1" stroke="none" fill="#FFFFFF"></rect><rect x="21" y="14" width="1.5" height="2" rx="1" stroke="none" fill="#FFFFFF"></rect></g></g></svg>
                                                {% endif %}
                                            </div>

                                            <div class="user-name">
                                                <h6>{{ user.fullname }}</h6>
                                                <span class="d-block">
                                                {{ user.getRoleName() }}
                                                    {% if user.isSuperAdmin() %} - {{ user.email }}{% endif %}
                                                    {% if user.isCandidat() %} - {{ user.getGroups()|join(' - ') }}{% endif %}
                                                </span>
                                            </div>
                                        </div>
                                    </a>
                                </li>
                            {% endif %}
                        {% endfor %}
                        <hr>
                    {% endfor %}
                </ul>
            {% else %}
                <ul class="list-group list-group-user list-unstyled mb-0">
                    {% for user in users %}
                        <li>
                            <a href="{{ path("read", {id: user.id}) }}">
                                <div class="d-flex align-items-center">
                                    <div class="avatar me-3">
                                        {% if user.profile and user.profile.getPhoto()|length %}
                                            {% for avatar in user.profile.getPhoto() %}
                                                {% if avatar.type is same as 1 %}
                                                    {% if loop.first %}
                                                        <img src="{{ asset('uploads/' ~ avatar.nom) }}" width="50" height="50" class="rounded-circle" alt="{{ user.getFullname() }}">
                                                    {% endif %}
                                                {% endif %}
                                            {% endfor %}
                                        {% else %}
                                            <svg viewBox="0 0 36 36" fill="none" role="img" xmlns="http://www.w3.org/2000/svg" width="50" height="50"><title>{{ app.user.getFullname()|capitalize }}</title><mask id="mask__beam" maskUnits="userSpaceOnUse" x="0" y="0" width="36" height="36"><rect width="36" height="36" fill="#FFFFFF" rx="72"></rect></mask><g mask="url(#mask__beam)"><rect width="36" height="36" fill="#dde3ca"></rect><rect x="0" y="0" width="36" height="36" transform="translate(3 5) rotate(261 18 18) scale(1)" fill="#487aa1" rx="36"></rect><g transform="translate(-5 1) rotate(-1 18 18)"><path d="M13,19 a1,0.75 0 0,0 10,0" fill="#FFFFFF"></path><rect x="13" y="14" width="1.5" height="2" rx="1" stroke="none" fill="#FFFFFF"></rect><rect x="21" y="14" width="1.5" height="2" rx="1" stroke="none" fill="#FFFFFF"></rect></g></g></svg>
                                        {% endif %}
                                    </div>

                                    <div class="user-name">
                                        <h6>{{ user.fullname }}</h6>
                                        <span class="d-block">{{ user.getRoleName() }}{% if user.isCandidat() %} - {{ user.getGroups()|join(' - ') }}{% endif %}</span>
                                    </div>
                                </div>
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
    </div>
</div>

<style>
    #myInput::-webkit-search-cancel-button{
        display: none;
    }
</style>
<script>
    function myFunction() {
        // Declare variables
        let input, filter, ul, li, a, i, txtValue;
        input = document.getElementById('myInput');
        filter = input.value.toUpperCase();
        ul = document.getElementById("myUL");
        li = ul.getElementsByTagName('li');

        // Loop through all list items, and hide those who don't match the search query
        for (i = 0; i < li.length; i++) {
            a = li[i].getElementsByTagName("a")[0];
            txtValue = a.textContent || a.innerText;
            if (txtValue.toUpperCase().indexOf(filter) > -1) {
                li[i].style.display = "";
            } else {
                li[i].style.display = "none";
            }
        }
    }
</script>